=== Altiia/sm-json-data/schema/m3-connection.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "title": "Super Metroid Connection Pathway Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "Connection Pathway Object",
    "required": [
      "area",
      "subarea",
      "id",
      "connections"
    ],
    "properties": {
      "area": {
        "$id": "#/items/properties/area",
        "type": "string",
        "title": "Area Name",
        "default": "",
        "examples": [
          "Brinstar"
        ],
        "pattern": "^(.*)$"
      },
      "subarea": {
        "$id": "#/items/properties/subarea",
        "type": "string",
        "title": "Area Subname",
        "default": "",
        "examples": [
          "Blue"
        ],
        "pattern": "^(.*)$"
      },
      "id": {
        "$id": "#/items/properties/id",
        "type": "integer",
        "title": "Room ID",
        "description": "Room ID in which the connections exist",
        "default": 0,
        "examples": [
          38
        ]
      },
      "connections": {
        "$id": "#/items/properties/connections",
        "type": "array",
        "title": "Connections; To + From",
        "items": {
          "$id": "#/items/properties/connections/items",
          "type": "object",
          "title": "The Items Schema",
          "required": [
            "id",
            "to"
          ],
          "properties": {
            "id": {
              "$id": "#/items/properties/connections/items/properties/id",
              "type": "integer",
              "title": "Node ID being linked from",
              "default": 0,
              "examples": [
                1
              ]
            },
            "to": {
              "$id": "#/items/properties/connections/items/properties/to",
              "type": "object",
              "title": "Node being linked to",
              "required": [
                "area",
                "subarea",
                "id"
              ],
              "properties": {
                "area": {
                  "$id": "#/items/properties/connections/items/properties/to/properties/area",
                  "type": "string",
                  "title": "Area Name",
                  "default": "",
                  "examples": [
                    "Brinstar"
                  ],
                  "pattern": "^(.*)$"
                },
                "subarea": {
                  "$id": "#/items/properties/connections/items/properties/to/properties/subarea",
                  "type": "string",
                  "title": "Area Subname",
                  "default": "",
                  "examples": [
                    "Green"
                  ],
                  "pattern": "^(.*)$"
                },
                "id": {
                  "$id": "#/items/properties/connections/items/properties/to/properties/id",
                  "type": "integer",
                  "title": "Room ID that this node links to",
                  "default": 0,
                  "examples": [
                    54
                  ]
                },
                "note": {
                  "$id": "#/items/properties/connections/items/properties/to/properties/note",
                  "type": "string",
                  "title": "The Note Schema",
                  "default": "",
                  "examples": [
                    "Room ID that this node within this Room connects to"
                  ],
                  "pattern": "^(.*)$"
                }
              }
            },
            "note": {
              "$id": "#/items/properties/connections/items/properties/note",
              "type": "string",
              "title": "The Note Schema",
              "default": "",
              "examples": [
                "Node ID of node within Room ID"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      },
      "note": {
        "$id": "#/items/properties/note",
        "type": "string",
        "title": "The Note Schema",
        "default": "",
        "examples": [
          "Room ID"
        ],
        "pattern": "^(.*)$"
      }
    }
  }
}

=== Altiia/sm-json-data/connection/crateria/west.json
[
  {
    "area": "Crateria",
    "subarea": "West",
    "id": 20,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 21
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 10
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "West",
    "id": 21,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 22
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 31
        }
      },
      {
        "id": 3,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 20
        }
      },
      {
        "id": 4,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 26
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "West",
    "id": 22,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 23
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 21
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "West",
    "id": 23,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Brinstar",
          "subarea": "Green",
          "id": 44
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 22
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "West",
    "id": 24,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 9
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "East",
          "id": 7
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "West",
    "id": 25,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 24
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Brinstar",
          "subarea": "Red",
          "id": 75
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "West",
    "id": 26,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 25
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 27
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "West",
    "id": 27,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 26
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Tourian",
          "subarea": "Main",
          "id": 224
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "West",
    "id": 30,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 31
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 8
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "West",
    "id": 31,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 21
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 30
        }
      }
    ]
  }
]

=== Altiia/sm-json-data/connection/ceres/main.json
[
  {
    "area": "Ceres Station",
    "subarea": "Ceres Station",
    "id": 1,
    "connections": [
      {
        "id": 2,
        "to": {
          "area": "Ceres Station",
          "subarea": "Ceres Station",
          "id": 2,
          "note": "Room ID that this node within this Room connects to"
        },
        "note": "Node ID of node within Room ID"
      }
    ],
    "note": "Room ID"
  },
  {
    "area": "Ceres Station",
    "subarea": "Ceres Station",
    "id": 2,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Ceres Station",
          "subarea": "Ceres Station",
          "id": 1
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Ceres Station",
          "subarea": "Ceres Station",
          "id": 3
        }
      }
    ]
  },
  {
    "area": "Ceres Station",
    "subarea": "Ceres Station",
    "id": 3,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Ceres Station",
          "subarea": "Ceres Station",
          "id": 2
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Ceres Station",
          "subarea": "Ceres Station",
          "id": 4
        }
      }
    ]
  },
  {
    "area": "Ceres Station",
    "subarea": "Ceres Station",
    "id": 4,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Ceres Station",
          "subarea": "Ceres Station",
          "id": 3
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Ceres Station",
          "subarea": "Ceres Station",
          "id": 5
        }
      }
    ]
  },
  {
    "area": "Ceres Station",
    "subarea": "Ceres Station",
    "id": 5,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Ceres Station",
          "subarea": "Ceres Station",
          "id": 4
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Ceres Station",
          "subarea": "Ceres Station",
          "id": 6
        }
      }
    ]
  },
  {
    "area": "Ceres Station",
    "subarea": "Ceres Station",
    "id": 6,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Ceres Station",
          "subarea": "Ceres Station",
          "id": 5
        }
      }
    ]
  }
]

=== Altiia/sm-json-data/connection/crateria/central.json
[
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 8,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 30
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 10
        }
      },
      {
        "id": 3,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 9
        }
      },
      {
        "id": 4,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 28
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 9,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 8
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 24
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 10,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "West",
          "id": 20
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 16
        }
      },
      {
        "id": 3,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 18
        }
      },
      {
        "id": 4,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 11
        }
      },
      {
        "id": 5,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 14
        }
      },
      {
        "id": 6,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 13
        }
      },
      {
        "id": 7,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 8
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 11,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Tourian",
          "subarea": "Main",
          "id": 242
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 12
        }
      },
      {
        "id": 3,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 29
        }
      },
      {
        "id": 4,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 29
        }
      },
      {
        "id": 5,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 10
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 12,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 11
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 306
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 13,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 10
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 19
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 14,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 10
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 15
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 15,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 14
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 16,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 10
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 17,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 18
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 18,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 17
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 10
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 19,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 13
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 28,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 8
        }
      }
    ]
  },
  {
    "area": "Crateria",
    "subarea": "Central",
    "id": 29,
    "connections": [
      {
        "id": 1,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 11
        }
      },
      {
        "id": 2,
        "to": {
          "area": "Crateria",
          "subarea": "Central",
          "id": 11
        }
      }
    ]
  }
]

=== Altiia/sm-json-data/connection/wreckedship/main.json
[
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 154,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Crateria",
            "subarea": "East",
            "id": 32
          }
        },
        {
          "id": 2,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 155
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 155,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 154
          }
        },
        {
          "id": 2,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 159
          }
        },
        {
          "id": 3,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 156
          }
        },
        {
          "id": 4,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 163
          }
        },
        {
          "id": 5,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 164
          }
        },
        {
          "id": 6,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 304
          }
        },
        {
          "id": 7,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 160
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 156,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 157
          }
        },
        {
          "id": 2,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 158
          }
        },
        {
          "id": 3,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 155
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 157,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 156
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 158,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 156
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 159,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 155
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 160,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Crateria",
            "subarea": "East",
            "id": 32
          }
        },
        {
          "id": 2,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 155
          }
        },
        {
          "id": 3,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 168
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 161,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Crateria",
            "subarea": "East",
            "id": 32
          }
        },
        {
          "id": 2,
          "to": {
            "area": "Crateria",
            "subarea": "East",
            "id": 32
          }
        },
        {
          "id": 3,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 162
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 162,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Crateria",
            "subarea": "East",
            "id": 32
          }
        },
        {
          "id": 2,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 161
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 163,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 155
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 164,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 155
          }
        },
        {
          "id": 2,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 165
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 165,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 164
          }
        },
        {
          "id": 2,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 166
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 166,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 167
          }
        },
        {
          "id": 2,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 165
          }
        },
        {
          "id": 3,
          "to": {
            "area": "Crateria",
            "subarea": "East",
            "id": 34
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 167,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 166
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 168,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 160
          }
        }
      ]
    },
    {
      "area": "Wrecked Ship",
      "subarea": "Main",
      "id": 304,
      "connections": [
        {
          "id": 1,
          "to": {
            "area": "Wrecked Ship",
            "subarea": "Main",
            "id": 155
          }
        }
      ]
    }
  ]
